# Freelancer Platform - Safe Validation Pipeline
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "=== SAFE RESOURCE VALIDATION ==="
    echo "Checking for configuration drift..."
    az deployment group what-if \
      --resource-group FreelancerPlatformRG \
      --template-file azuredeploy.json \
      --parameters location=northeurope
    echo "Validation complete. No changes deployed."
  displayName: 'Validate Infrastructure'
  env:
    AZURE_CREDENTIALS: $(AZURE_CREDENTIALS)
