trigger: none  # Disable automatic runs to save minutes

pool:
  vmImage: 'ubuntu-latest'
  demands:    # Forces free-tier compatibility
  - Agent.Name -equals $(Agent.Name)

steps:
- script: |
    echo "Running in free tier mode..."
    az --version
  displayName: 'Validate Setup'
