# Ultra-simple pipeline that always works in free tier
trigger: none  # Manual runs only

pool:
  vmImage: 'ubuntu-20.04'  # More stable than 'latest'
  name: 'Azure Pipelines'  # Explicit free pool

steps:
- script: |
    echo "=== BASIC VALIDATION ==="
    echo "This pipeline is designed to:"
    echo "1. Bypass parallelism errors"
    echo "2. Prove Azure DevOps is working"
    echo "3. Prepare for next steps"
    echo "Agent OS: $(uname -a)"
  displayName: 'Free Tier Validation'
