trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'FreelancerPlatform-Azure' # Match service connection name

steps:
- task: AzureCLI@2
  displayName: 'Validate Infrastructure'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "=== SAFE VALIDATION ==="
      az deployment group what-if \
        --resource-group FreelancerPlatformRG \
        --template-file azuredeploy.json \
        --parameters location=northeurope
      echo "Validation complete."
